# Generated by Django 4.2.6 on 2023-10-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="story", name="created_at",),
        migrations.AlterField(
            model_name="story", name="title", field=models.CharField(max_length=200),
        ),
    ]
